name: Auto Dummy Commit

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Gitリポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          persist-credentials: false  

      - name: ユーザー情報追加
        run: |
          git config --global user.email "sasasanono@outlook.jp"
          git config --global user.name "sakiyamamamama"

      - name: ダミー変更を追加
        run: |
          echo "$(date)" > dummy.txt
          git add dummy.txt
          git commit -m "chore: dummy commit $(date)"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/sakiyamamamama/horizon-atlas.git
          git push origin main
