name: Auto Dummy Commit

on:
  schedule:
    - cron: "0 0 * * *"  # 毎日UTC 0時（日本時間9時）に実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Gitリポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: ユーザー情報追加
        run: |
          git config --global user.email "sasasanono@outlook.jp"
          git config --global user.name "sakiyamamamama"

      - name: ダミー変更を追加
        run: |
          echo "$(date)" > dummy.txt  # 日時を書き込む
          git add dummy.txt
          git commit -m "chore: dummy commit $(date)"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/sakiyamamamama/horizon-atlas.git
          git push origin main
