name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main  # main ブランチに push したらデプロイ

permissions:
  contents: write  # GitHub Pages にデプロイするために必要

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 依存関係をインストール
        run: npm install

      - name: Next.js をビルド
        run: npm run build
        env:
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NOTION_DATABASE_ID2: ${{ secrets.NOTION_DATABASE_ID2}}
          NOTION_TOKEN2: ${{ secrets.NOTION_TOKEN2}}
          DISCORD_HORIZON_ID: ${{ secrets.DISCORD_HORIZON_ID}}
          DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET}}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID}}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}

      - name: GitHub Pages 用にエクスポート
        run: npm run export

      - name: gh-pages ブランチにデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: main
